version: '3.8'

services:
  mysql-db:
    image: mysql:8.0
    container_name: mysql-db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: payment_service_db
      MYSQL_USER: mateuzzo
      MYSQL_PASSWORD: payment123*
    ports:
      - "3306:3306"
    networks:
      - bank-payment-network

  postgres-db:
    image: postgres:13
    container_name: postgres-db
    environment:
      POSTGRES_DB: payment_service_db_test
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    networks:
      - bank-payment-network

networks:
  bank-payment-network:
    driver: bridge

